services:
  scopus-recsys-init:
    user: root
    image: scopus-recsys:0.1
    platform: linux/amd64  # Specify the platform if needed
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATA_PATH=/data
      - EMBEDDING_DIM=384
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    command: uv run main.py init

  scopus-recsys-classify:
    user: root
    image: scopus-recsys:0.1
    platform: linux/amd64  # Specify the platform if needed
    environment:
      - DATA_PATH=/data
      - LLM=llama3.2:1b
      - OLLAMA_HOST=scopus-recsys-ollama
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    command: uv run main.py classify
    networks:
      - scopus-recsys-network
    depends_on:
      - scopus-recsys-ollama

  scopus-recsys-similarity-algorithm:
    user: root
    image: scopus-recsys:0.1
    platform: linux/amd64  # Specify the platform if needed
    environment:
      - DATA_PATH=/data
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    command: uv run main.py similarity-algorithm

  scopus-recsys-similarity-application:
    user: root
    image: scopus-recsys:0.1
    platform: linux/amd64  # Specify the platform if needed
    environment:
      - DATA_PATH=/data
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    command: uv run main.py similarity-application

  scopus-recsys-algorithm-application-link:
    user: root
    image: scopus-recsys:0.1
    platform: linux/amd64  # Specify the platform if needed
    environment:
      - DATA_PATH=/data
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    command: uv run main.py algorithm-application-link

  scopus-recsys-ollama:
    user: root
    image: ollama/ollama:0.5.13
    platform: linux/amd64  # Specify the platform if needed
    volumes:
      - ./data/:/data
      - ./src/job/:/app/src/job
    networks:
      - scopus-recsys-network
    ports:
      - "11434:11434"

networks:
  scopus-recsys-network:
    driver: bridge
